name: permission_handler_pkg
description: permission_handler

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.0.1
  mocktail: ^1.0.1

  # Modules
  dependency_interfaces:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3

