name: logger_pkg
description: logger

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.2
  path_provider: ^2.1.1
  rxdart: ^0.27.7

  # Modules
  dependency_interfaces:

dev_dependencies:
  flutter_test:
    sdk: flutter
