name: harmony_app
description: "."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  async_builder: ^1.3.1+1
  collection: ^1.17.1
  get_it: ^7.6.4
  rxdart: ^0.27.7
  fast_immutable_collections: ^9.2.0
  nil: ^1.1.1
  comprehensive_utils: ^0.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  async: ^2.11.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  flutter_animate: ^4.3.0
  # Modules
  dependency_interfaces:
  localization_pkg:
  permission_handler_pkg:
  library_pkg:
  background_worker_pkg:
  local_storage_pkg:
  rest_client_pkg:
  logger_pkg:
  platform_info_pkg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/libra/left_wage.png
    - assets/libra/right_wage.png
    - assets/libra/main_wage.png
    - assets/libra/wage_bar.png
